# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'ubuntu-20.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: Cache@2
    inputs:
      key: 'npm | $(Agent.OS) | yarn.lock'
      path: '/home/vsts/.npm'
      restoreKeys: 'npm | $(Agent.OS) | yarn.lock'
    displayName: 'Cache NPM packages'

  - task: Cache@2
    inputs:
      key: 'npm | $(Agent.OS) | yarn.lock'
      path: '/home/vsts/.cache/Cypress'
      restoreKeys: 'npm | $(Agent.OS) | yarn.lock'
    displayName: 'Cache Cypress packages'

  - script: |
      yarn install
    displayName: 'Install npm dependencies'

  - script: |
      yarn lint
    displayName: 'Lint code'

  - script: |
      yarn coverage
    displayName: 'Run test with coverage'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/.coverage/cobertura-coverage.xml'

  - script: |
      yarn build
    displayName: 'Build production build'

  - script: |
      yarn run ci
    displayName: 'Run Cypress tests'
    env:
      # avoid warnings about terminal
      TERM: xterm
